apiVersion: v1
kind: Service
metadata:
  name: damocapstonepro
#  namespace: eks-capstone-ns
  labels:
    app: damocapstonepro
spec:
  type: LoadBalancer
  selector:
    app: damocapstonepro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80